<?php
  //print_r($_POST['case']);

  require_once 'dompdf/autoload.inc.php';
  // reference the Dompdf namespace
  use Dompdf\Dompdf;

  $conn = mysqli_connect('localhost', 'obqnffzy_admin', 'PollY@820829', 'obqnffzy_luxit');

  $sql = "SELECT * FROM bills WHERE bill_id='".$_POST['case']."'";
  $run = mysqli_query($conn, $sql);
  $bill = mysqli_fetch_all($run, MYSQLI_ASSOC)[0];
  $disbursement;

  $division = strtoupper($bill['division']);
  $caseNr = $_POST['case'];
  $pORa = $bill['pa'];
  $dORr = $bill['dr'];
  $pORaName = $bill['plain_name'];
  $dORrName = $bill['def_name'];
  $compName = strtoupper($bill['comp']);
  $actingFor = strtoupper($bill['att_for']);
  $scale = strtoupper($bill['scale']);
  $rate = $bill['hr'];

  $sql2 = "SELECT * FROM bill_item WHERE parent_bill='".$_POST['case']."' ORDER BY date ASC";
  $run2 = mysqli_query($conn, $sql2);
  $items = mysqli_fetch_all($run2, MYSQLI_ASSOC);
  // instantiate and use the dompdf class
  $dompdf = new Dompdf();
  $html .= '<link rel="stylesheet" type="text/css" href="css/main.css">';
  $html .= '<link rel="stylesheet" type="text/css" href="css/pdf.css">';
  $html .= '<script type="text/javascript" src="js/main.js"></script>';
  $html .= "<div class='header jumbotron head'>";
  $html .=  "<div class='container'>";
  $html .=  "<div class='row row-1'>";
  $html .=  "<p class='col-sm-12'><b>IN THE HIGH COURT OF SOUTH AFRICA</b></p>";
  $html .=  "<p id='div' class='col-sm-12 under'><b>GAUTENG DIVISION - ".$division."</b></p>";
  $html .=  "<p id='case'  class='col-sm-12 right'><b>CASE NR:".$caseNr."</b></p>";
  $html .=  "<p class='col-sm-12 left'>In the matter between</p>";
  $html .=  "<p id='p1' class='col-sm-6 left'><b>".$pORaName."</b></p>";
  $html .=  "<p id='pa' class='col-sm-6 right'><b>".$pORa."</b></p>";
  $html .=  "<p class='col-sm-12 left'>and</p>";
  $html .=  "<p id='p2' class='col-sm-6 left'><b>".$dORrName."</b></p>";
  $html .=  "<p id='dr' class='col-sm-6 right'><b>".$dORr."</b></p>";
  $html .=  "</div>";
  $html .=  "</div>";
  $html .=  "</div>";
  $html .=  "<p class='jumbotron memo-msg'><b>MEMORANDUM OF FEES AND DISBURSEMENTS DUE TO ".$compName." ATTORNEYS, INSTRUCTING ATTORNEYS FOR ".$actingFor.", AS ON A SCALE BETWEEN ".$scale." - FOR PROFESSIONAL SERVICES RENDERED<b></p>";
  $html .=  "<div style='width:100%;' class='tabel'>";

  $totalFees = 0;
  $totaldisb = 0;
	$count = 0;
  foreach ($items as $key => $item) {
    $info;
    $amount;
    if($item['disbursement'] != null && $item['disbursement'] >= 0) {
      $disbursement = $item['disbursement'];
      $totaldisb += $disbursement;
    }else {
      $disbursement = '';
    }
    if($item["info_add"] != null) {
      if(strpos($item["information"], "#") !== false) {
        $info = str_replace("#",$item["info_add"],$item["information"]);
      }else {
        $info = $item["information"].$item["info_add"];
      }
    }else {
      $info = $item["information"];
    }
    if($item["pm"] == "pg") {
      $amount = ((int)$item["amount"]*(int)$item["per_amount"]);
    }elseif($item["pm"] == "min") {
      $amount = ((int)$item["amount"]/60*(int)$rate);
    }else {
      $amount = $item['amount'];
    }
    $totalFees += $amount;
    $count += 1;
    $lastID = ( $key !== count( $items ) -1 ) ? "" : "last";
    $html .= '<div class=" tabel-ry " style="width:100%;">';
    $html .= '  <div class="tabel-sel table-date border-right twenty">'.$item["date"].'</div>';
    $html .= '  <div id="'.$lastID.'" class="tabel-sel table-nr border-right">'.$count.'</div>';
    $html .= '  <div class="tabel-sel table-desc left border-noleft">'.$info.'</div>';
    $html .= '  <div class="tabel-sel table-fee singledouble ten">'.number_format((float)$amount, 2, '.', '').'</div>';
    $html .= '  <div id="'.$count.'" class="tabel-sel table-dist ten">'.number_format((float)$disbursement, 2, '.', '').'</div>';
    $html .= '</div>';
    $html .= '<div class=" tabel-ry " style="width:100%;">';
    $html .= "  <span class='tabel-sel table-date border-right'></span>";
    $html .= "  <span class='tabel-sel table-nr border-right'></span>";
    $html .= "  <span class='tabel-sel table-desc left border-noleft'></span>";
    $html .= "  <span class='tabel-sel table-fee singledouble'></span>";
    $html .= "  <span class='tabel-sel table-dist '></span>";
    $html .= "</div>";
  }
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel table-date border-right'></span>";
  $html .=  "          <span class='tabel-sel table-nr border-right'></span>";
  $html .=  "          <span class='tabel-sel table-desc left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel table-fee singledouble'></span>";
  $html .=  "          <span class='tabel-sel table-dist '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel table-date border-right'></span>";
  $html .=  "          <span class='tabel-sel table-nr border-right'></span>";
  $html .=  "          <span class='tabel-sel table-desc left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel table-fee singledouble'></span>";
  $html .=  "          <span class='tabel-sel table-dist '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel table-date border-right'></span>";
  $html .=  "          <span class='tabel-sel table-nr border-right'></span>";
  $html .=  "          <span class='tabel-sel table-desc left border-noleft'><b>BALANCE BROUGHT FORWARD (A) & (B)</b></span>";
  $html .=  '          <span class="tabel-sel table-fee singledouble">'.number_format((float)$totalFees, 2, '.', '').'</span>';
  $html .=  "          <span id='totalDisb' class='tabel-sel table-dist '>".number_format((float)$totaldisb, 2, '.', '')."</span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel table-date border-right'></span>";
  $html .=  "          <span class='tabel-sel table-nr border-right'></span>";
  $html .=  "          <span class='tabel-sel table-desc left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel table-fee singledouble'></span>";
  $html .=  "          <span class='tabel-sel table-dist '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel table-date border-right'></span>";
  $html .=  "          <span class='tabel-sel table-nr border-right'></span>";
  $html .=  "          <span class='tabel-sel table-desc left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel table-fee singledouble'></span>";
  $html .=  "          <span class=' table-dist'></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel table-date border-right'></span>";
  $html .=  "          <span class='tabel-sel table-nr border-right'></span>";
  $html .=  "          <span class='tabel-sel table-desc left border-noleft'>MINUS TAXED OFF</span>";
  $html .=  "          <span class='tabel-sel table-fee singledouble bottomdouble'></span>";
  $html .=  "          <span class='tabel-sel table-dist bottomdouble'></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel table-date border-right'></span>";
  $html .=  "          <span class='tabel-sel table-nr border-right'></span>";
  $html .=  "          <span class='tabel-sel table-desc left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel table-fee singledouble'></span>";
  $html .=  "          <span class='tabel-sel table-dist '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel table-date border-right'></span>";
  $html .=  "          <span class='tabel-sel table-nr border-right'></span>";
  $html .=  "          <span class='tabel-sel table-desc left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel table-fee singledouble'></span>";
  $html .=  "          <span class='tabel-sel table-dist '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel table-date border-right'></span>";
  $html .=  "          <span class='tabel-sel table-nr border-right'></span>";
  $html .=  "          <span class='tabel-sel table-desc left border-noleft'><b>SUB TOTAL</b></span>";
  $html .=  "          <span class='tabel-sel table-fee singledouble'></span>";
  $html .=  "          <span class='tabel-sel table-dist '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'>PLUS DRAWING FEE</span>";
  $html .=  "          <span class='tabel-sel singledouble bottomdouble'></span>";
  $html .=  "          <span class='tabel-sel border-no'></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'><b>SUB TOTAL</b></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel border-no'></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'>PLUS DISBURSEMENTS</span>";
  $html .=  "          <span class='tabel-sel singledouble bottomdouble'></span>";
  $html .=  "          <span class='tabel-sel border-no'></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'><b>SUB TOTAL</b></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel border-no'></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'>PLUS FEE ATTENDING TAXATION</span>";
  $html .=  "          <span class='tabel-sel singledouble bottomdouble'></span>";
  $html .=  "          <span class='tabel-sel border-no'></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'><b>SUB TOTAL</b></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel border-no'></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'>PLUS 14% VAT ON FEES <i>before 1 April 2018</i> <b>(Subtotal on Fees R_____________)(A)</b></span>";
  $html .=  "          <span class='tabel-sel singledouble bottomdouble'></span>";
  $html .=  "          <span class='tabel-sel border-no'></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .= '         <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'>PLUS 15% VAT ON FEES <i>after 1 April 2018</i> <b>(Subtotal on Fees R_____________)(A)</b></span>";
  $html .=  "          <span class='tabel-sel singledouble bottomdouble'></span>";
  $html .=  "          <span class='tabel-sel border-no'></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'><b>TOTAL DUE</b></span>";
  $html .=  "          <span class='tabel-sel bottomdouble singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'><b>TAXED AND ALLOWED IN THE AMOUNT OF</b></span>";
  $html .=  "          <span colspan='2' class='tabel-sel top-sides'><label class='center'><b>Case nr:</b></label></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'><b>TAXED AND ALLOWED IN THE AMOUNT OF</b></span>";
  $html .=  "          <span colspan='2' class='tabel-sel bottom-sides'><label class=' center'>".$caseNr."</label></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'>R__________________________</span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left bottomdouble border-noleft'></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  '       <div class=" tabel-ry " style="width:100%;">';
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel border-right'></span>";
  $html .=  "          <span class='tabel-sel left border-noleft'><b>TAXING MASTER</b></span>";
  $html .=  "          <span class='tabel-sel singledouble'></span>";
  $html .=  "          <span class='tabel-sel '></span>";
  $html .=  "        </div>";
  $html .=  "  </div>";
  /*$html .=  '  <div class="tablok tabel" style="width:100%;">';
  $html .=  '         <div class=" tabel-ry blok" style="width:100%;">';
  $html .=  "           <b><p class='tabel-sel'><u>Settlement endorsement in terms of Rule 70 of the High Court Uniform Rules:</u></p></b>";
  $html .=  "         </div>";
  $html .=  '         <div class=" tabel-ry blok" style="width:100%;">';
  $html .=  "          <b><p class='tabel-sel'>Settled between *user* abo __________________________________________________and</p></b>";
  $html .=  "         </div>";
  $html .=  '         <div class=" tabel-ry blok" style="width:100%;">';
  $html .=  "          <b><p class='tabel-sel'> __________________________________________________from __________________________________________________</p></b>";
  $html .=  "         </div>";
  $html .=  '         <div class=" tabel-ry blok" style="width:100%;">';
  $html .=  "          <b><p class='tabel-sel'>on this the ______ day of  _________________________ 2020.</p></b>";
  $html .=  "         </div>";
  $html .=  '         <div class=" tabel-ry blok" style="width:100%;">';
  $html .=  "          <b><p class='tabel-sel'>Contact info of *user at company* - tel: *tel*</p></b>";
  $html .=  "         </div>";
  $html .=  '         <div class=" tabel-ry blok" style="width:100%;">';
  $html .=  "          <b><p class='tabel-sel'>Contact info of  __________________________________________________ at  __________________________________________________ -tel:</p></b>";
  $html .=  "         </div>";
  $html .=  '         <div class=" tabel-ry blok" style="width:100%;">';
  $html .=  "          <b><p class='tabel-sel'> _________________________</p></b>";
  $html .=  "         </div>";
  $html .=  "  </div>";*/
  $dompdf->loadHtml($html);

  // (Optional) Setup the paper size and orientation
  $dompdf->setPaper('A4', 'portrait');
  // Render the HTML as PDF
  $dompdf->render();

  $filename = str_replace("/","_",$caseNr) . " BillOfCost";

  // Output the generated PDF to Browser
  $dompdf->stream($filename, 0);

?>
